    .section .rodata
    .globl _binary_boards_waveshare_p4_nano_FsOoJPJC10BiOchqCIN1ZnU4DTEi_jpg_start
    .globl _binary_boards_waveshare_p4_nano_FsOoJPJC10BiOchqCIN1ZnU4DTEi_jpg_end

    .extern _binary_FsOoJPJC10BiOchqCIN1ZnU4DTEi_jpg_start
    .extern _binary_FsOoJPJC10BiOchqCIN1ZnU4DTEi_jpg_end

    .set _binary_boards_waveshare_p4_nano_FsOoJPJC10BiOchqCIN1ZnU4DTEi_jpg_start, _binary_FsOoJPJC10BiOchqCIN1ZnU4DTEi_jpg_start
    .set _binary_boards_waveshare_p4_nano_FsOoJPJC10BiOchqCIN1ZnU4DTEi_jpg_end,   _binary_FsOoJPJC10BiOchqCIN1ZnU4DTEi_jpg_end
